version: "3"

services:
  tp1:
    container_name: teamplay1
    image: replace_with_image_reference_from_readme
    # ports to map to host, cannot be in use and must correspond to same value as PORT variable in tp1.env
    ports:  
      - "27910:27910/udp"
      - "27910:27910/tcp"
    stdin_open: true
    tty: true
    restart: unless-stopped
    # set server parameters in env_file
    env_file:
      - ./tp1.env  
    # set your local timezone
    environment:
      - TZ=Etc/UTC
    # mounts to allow access and persist files on host, you will need to set appropriate permissions
    volumes:
      - ./tp1.motd:/aq2server/action/motd.txt:ro
      - maps:/aq2server/action/maps
      - logs:/aq2server/action/logs
      - demos:/aq2server/action/demos

volumes:
  maps:
  logs:
  demos:
