name: build_linux

# on:
#   push:
#     branches: [main, ci]
#   pull_request:
#     branches: [main]

on:
  push:
    branches: [branchthatdoesntexist]

jobs:
  linux_build_q2pro:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cc: [gcc]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: skullernet/q2pro
          path: build

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install -y libsdl2-dev libopenal-dev \
          libpng-dev libjpeg-dev zlib1g-dev mesa-common-dev \
          libcurl4-gnutls-dev

      - name: Whereami
        run: ls -l

      - name: Build Q2Pro
        working-directory: build
        run: make V=1
        env:
          CC: "${{ matrix.cc }}"
          CONFIG_FILE: "ci/config_linux64"
      
      - name: Generate archive
        uses: actions/upload-artifact@v3
        with:
          name: q2pro-executables
          path: |
            q2pro
            q2proded
