name: build_linux

on:
  push:
    branches: [main, ci]
  pull_request:
    branches: [main]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cc: [gcc, clang]
    steps:
      - uses: actions/checkout@v3
        repository: https://github.com/skullernet/q2pro.git
        with:
          path: build

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install -y libsdl2-dev libopenal-dev \
          libpng-dev libjpeg-dev zlib1g-dev mesa-common-dev \
          libcurl4-gnutls-dev

      - name: Build
        working-directory: build
        run: make V=1
        env:
          CC: "${{ matrix.cc }}"
          CONFIG_FILE: ".ci/config_linux"