name: build_tng_windows

# on:
#   push:
#     branches: [main, ci]
#   pull_request:
#     branches: [main]

on:
  workflow_dispatch:

jobs:
  windows_build_tng:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          repository: aq2-tng/aq2-tng
          ref: 'bots'
          path: build

      - uses: actions/checkout@v3
        with:
          repository: actionquake/distrib
          path: config

      # This is because the Makefile doesn't recognize mingw on Linux, and we have to append a special flag at the linking step for Windows
      - name: Rough hack to fix Makefile
        run: |
          mv build/source/Makefile build/source/Makefile-original
          cat config/build/ci/tng-windows-append build/source/Makefile-original > build/source/Makefile

      - name: Build TNG (64-bit)
        working-directory: build/source
        run: make V=1
        env:
          IFDEF: "WIN64"

      - name: Save Win64 artifact
        working-directory: build/source
        run: |
          mkdir dist
          cp gamex86_64.dll dist/gamex86_64.dll
          make clean

      - name: Build TNG (32-bit)
        working-directory: build/source
        run: make V=1
        env:
          IFDEF: "WIN32"

      - name: Save Win32 artifact
        working-directory: build/source
        run: |
          cp gamex86.dll dist/gamex86.dll
      
      - name: Generate archive
        uses: actions/upload-artifact@v3
        with:
          name: tng-win-libraries
          path: |
            build/source/dist/*.dll
