name: build_tng_windows

# on:
#   push:
#     branches: [main, ci]
#   pull_request:
#     branches: [main]

on:
  workflow_dispatch:

jobs:
  linux:
    runs-on: self-hosted
    strategy:
      matrix:
        cc: [i686-w64-mingw32-gcc, x86_64-w64-mingw32-gcc]
        strip: [i686-w64-mingw32-strip, x86_64-w64-mingw32-strip]
        windres: [i686-w64-mingw32-windres, x86_64-w64-mingw32-windres] 

    steps:
      - uses: actions/checkout@v3
        with:
          repository: aq2-tng/aq2-tng
          ref: 'bots'
          path: build

      - name: Build TNG
        working-directory: build/source
        run: make V=1
        env:
          CC: "${{ matrix.cc }}"
          STRIP: "${{ matrix.strip }}"
          WINDRES: "${{ matrix.windres }}"

      - name: Generate archive
        uses: actions/upload-artifact@v3
        with:
          name: tng-win-library
          path: |
            build/source/gamex*