name: Mac Artifacts

on:
  push:
    branches: ci

# on:
#   workflow_dispatch:
#     inputs:
#       release_tag:
#         description: "Release version tag"
#         required: true

env:
  CFG_WORKING_DIR: "config"

jobs:      
  generate_mac_artifacts:
    runs-on: macos-latest
    steps:
      - name: Checkout distrib
        uses: actions/checkout@v3
        with:
          repository: actionquake/distrib
          path: ${{ env.CFG_WORKING_DIR }}

      - name: Generate Mac Intel artifacts
        working-directory: ${{ env.CFG_WORKING_DIR }}/build/mac
        run: bash package_mac.sh intel
        
      - name: Generate Mac m1 artifacts
        working-directory: ${{ env.CFG_WORKING_DIR }}/build/mac
        run: bash package_mac.sh m1

      - name: Generate Intel DMG artifact
        uses: actions/upload-artifact@v3
        with:
          name: mac-intel-dmg
          path: |
            ${{ env.CFG_WORKING_DIR }}/build/mac/aqtion-mac-intel.dmg

      - name: Generate M1 DMG artifact
        uses: actions/upload-artifact@v3
        with:
          name: mac-m1-dmg
          path: |
            ${{ env.CFG_WORKING_DIR }}/build/mac/aqtion-mac-m1.dmg

      - name: Generate Intel zip artifact
        uses: actions/upload-artifact@v3
        with:
          name: mac-intel-zip
          path: |
            ${{ env.CFG_WORKING_DIR }}/build/mac/aqtion-mac-intel.zip

      - name: Generate M1 zip artifact
        uses: actions/upload-artifact@v3
        with:
          name: mac-m1-zip
          path: |
            ${{ env.CFG_WORKING_DIR }}/build/mac/aqtion-mac-m1.zip