name: Mac Artifacts

# on:  
#   push:
#     tags:
#       - 'v*'

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release version tag"
        required: true

env:
  CFG_WORKING_DIR: "config"
  GIT_TAG: ${{github.ref_name}}

jobs:      
  generate_mac_artifacts:
    runs-on: macos-latest
    steps:
      - name: Checkout distrib
        uses: actions/checkout@v3
        with:
          repository: actionquake/distrib
          path: ${{ env.CFG_WORKING_DIR }}

      - name: Generate Mac Intel DMG
        working-directory: ${{ env.CFG_WORKING_DIR }}/build/mac
        run: bash dmg_mac.sh intel ${{github.ref_name}}
        env:
          CI: "true"
        
      - name: Generate Mac m1 DMG
        working-directory: ${{ env.CFG_WORKING_DIR }}/build/mac
        run: bash dmg_mac.sh m1 ${{github.ref_name}}
        env:
          CI: "true"

      - name: Generate archives
        uses: actions/upload-artifact@v3
        with:
          name: mac-intel-dmg
          path: |
            ${{ env.CFG_WORKING_DIR }}/build/mac/aqtion-${{github.ref_name}}-mac-intel.dmg

      - name: Generate archives
        uses: actions/upload-artifact@v3
        with:
          name: mac-m1-dmg
          path: |
            ${{ env.CFG_WORKING_DIR }}/build/mac/aqtion-${{github.ref_name}}-mac-m1.dmg

      - name: Upload dist dmgs to release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          body_path: 
          tag_name: ${{github.ref_name}}
          files: |
            ${{ env.CFG_WORKING_DIR }}/build/mac/aqtion-${{github.ref_name}}-mac-intel.dmg
            ${{ env.CFG_WORKING_DIR }}/build/mac/aqtion-${{github.ref_name}}-mac-m1.dmg
      
    

