name: Mac Artifacts

on:
  push:
    branches: ci

# on:
#   workflow_dispatch:
#     inputs:
#       release_tag:
#         description: "Release version tag"
#         required: true

env:
  CFG_WORKING_DIR: "config"

jobs:      
  generate_mac_artifacts:
    runs-on: macos-latest
    steps:
      - name: Checkout distrib
        uses: actions/checkout@v3
        with:
          repository: actionquake/distrib
          path: ${{ env.CFG_WORKING_DIR }}

      - name: Generate Mac artifacts
        working-directory: ${{ env.CFG_WORKING_DIR }}/build/mac
        run: bash package_mac.sh

      - name: Generate Universal DMG artifact
        uses: actions/upload-artifact@v3
        with:
          name: mac-universal-dmg
          path: |
            ${{ env.CFG_WORKING_DIR }}/build/mac/aqtion-mac-universal.dmg

      - name: Generate Universal zip artifact
        uses: actions/upload-artifact@v3
        with:
          name: mac-universal-zip
          path: |
            ${{ env.CFG_WORKING_DIR }}/build/mac/aqtion-mac-universal.zip
