name: Mac Artifacts

# on:  
#   push:
#     tags:
#       - 'v*'

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release version tag"
        required: true

env:
  CFG_WORKING_DIR: "config"
  GIT_TAG: ${{ github.event.inputs.release_tag }}

jobs:      
  generate_mac_artifacts:
    runs-on: macos-latest
    steps:
      - name: Checkout distrib
        uses: actions/checkout@v3
        with:
          repository: actionquake/distrib
          path: ${{ env.CFG_WORKING_DIR }}

      - name: Generate Mac Intel DMG
        working-directory: ${{ env.CFG_WORKING_DIR }}/build/mac
        run: bash standalone_mac.sh intel ${{ env.GIT_TAG }}
        env:
          CI: "true"
        
      - name: Generate Mac m1 DMG
        working-directory: ${{ env.CFG_WORKING_DIR }}/build/mac
        run: bash standalone_mac.sh m1 ${{ env.GIT_TAG }}
        env:
          CI: "true"

      - name: Generate Intel artifact
        uses: actions/upload-artifact@v3
        with:
          name: mac-intel-dmg
          path: |
            ${{ env.CFG_WORKING_DIR }}/build/mac/aqtion-${{ env.GIT_TAG }}-mac-intel.dmg

      - name: Generate M1 artifact
        uses: actions/upload-artifact@v3
        with:
          name: mac-m1-dmg
          path: |
            ${{ env.CFG_WORKING_DIR }}/build/mac/aqtion-${{ env.GIT_TAG }}-mac-m1.dmg
