name: New Content Release

on:
  push:
    branches: ci
  workflow_dispatch:

env:
  CFG_WORKING_DIR: "config"

jobs:      
  generate_content_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout distrib
        uses: actions/checkout@v3
        with:
          repository: actionquake/distrib
          path: ${{ env.CFG_WORKING_DIR }}

      - name: Zip game content to pkz
        working-directory: ${{ env.CFG_WORKING_DIR }}/action
        run: |
          for makepkz in default-configs default-game-content default-hdtextures default-mappack0 default-mappack1 default-pics default-sounds; do
            cd ${makepkz}
            zip -r ../0_${makepkz}.pkz * && cd ..
            rm -rf ${makepkz}/
          done

      - name: Download all library files for Windows, Linux and Linux ARM
        run: |
          for FILE in tng-win-64 tng-lin-x86_64 tng-lin-arm64; do wget -qnv https://github.com/actionquake/aq2-tng/releases/latest/download/${FILE}.zip && unzip -o ${FILE}.zip -d ${{ env.CFG_WORKING_DIR }}/action/; rm -rf ${FILE}.zip; done

      - name: Generate dist files
        run: |
          cd ${{ env.CFG_WORKING_DIR }} && zip -r aqtion-content.zip versions action/

      - name: Generate archive
        uses: actions/upload-artifact@v3
        with:
          name: aq-content-only
          path: |
            ${{ env.CFG_WORKING_DIR }}/aqtion-content.zip

      - name: 'Post-build cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./
