name: New Dist Release

# on:
#   push:
#     branches: ci
#   workflow_dispatch:

on:  
  push:
    tags:
      - 'v*'

env:
  AQTION_DIR: aqtion
  DIST_DIR: config
  GIT_TAG: ${{github.ref_name}}

jobs:
  content_only:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout distrib
        uses: actions/checkout@v3
        with:
          repository: actionquake/distrib
          path: ${{ env.DIST_DIR }}

      - name: Generate directory structure
        run: |
          mkdir -p ${{ env.AQTION_DIR }}/action

      - name: Zip game content to pkz
        working-directory: ${{ env.DIST_DIR }}/action
        run: |
          for makepkz in default-configs default-game-content default-hdtextures default-mappack0 default-mappack1 default-pics default-sounds; do
            cd ${makepkz}
            zip -r ../0_${makepkz}.pkz * && cd ..
            rm -rf ${makepkz}/
          done
      
      # - name: Generate checksum file
      #   working-directory: ${{ env.DIST_DIR }}/action
      #   run: |
      #     find -type f \( -not -name "checksums" \) -exec md5sum '{}' \; > checksums

      - name: Download all library files for Windows, Linux and Linux ARM
        run: |
          for FILE in tng-win-64 tng-lin-x86_64 tng-lin-arm64; do wget -qnv https://github.com/actionquake/aq2-tng/releases/latest/download/${FILE}.zip && unzip -o ${FILE}.zip -d ${{ env.DIST_DIR }}/action/; rm -rf ${FILE}.zip; done

      - name: Copy aqtion content
        run: |
          cp ${{ env.DIST_DIR }}/LICENSE ${{ env.AQTION_DIR }}
          cp -r ${{ env.DIST_DIR }}/action/* aqtion/action/

      - name: Upload aqtion content artifact
        uses: actions/upload-artifact@v3
        with:
          name: aqtion-${{github.ref_name}}-content-only
          path: |
            ${{ env.AQTION_DIR }}

      - name: Generate release artifact
        run: |
          zip -r aqtion-${{github.ref_name}}-content-only.zip ${{ env.AQTION_DIR }}

      - name: Upload dist tarball to release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          body_path: 
          tag_name: ${{github.ref_name}}
          files: |
            aqtion-${{github.ref_name}}-content-only.zip

  linux_deb:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          repository: actionquake/distrib
          path: ${{ env.DIST_DIR }}

      - name: Generate Linux deb files
        working-directory: ${{ env.DIST_DIR }}/build/linux
        run: |
          sed -i "s/version_value_here/${GIT_TAG:1}/g" dpkg/DEBIAN/control
          cp -r dpkg aqtion-${{github.ref_name}}-linux-x86_64
          cp -r dpkg aqtion-${{github.ref_name}}-linux-arm64
          sed -i "s/arch_value_here/x86_64/g" aqtion-${{github.ref_name}}-linux-x86_64/DEBIAN/control
          sed -i "s/arch_value_here/arm64/g" aqtion-${{github.ref_name}}-linux-arm64/DEBIAN/control
          dpkg-deb --build --root-owner-group aqtion-${{github.ref_name}}-linux-x86_64
          dpkg-deb --build --root-owner-group aqtion-${{github.ref_name}}-linux-arm64
          mv aqtion-${{github.ref_name}}-linux-* ../../../

      - name: Generate Linux x86_64 deb archive
        uses: actions/upload-artifact@v3
        with:
          name: linux-${{github.ref_name}}-x86_64-deb
          path: |
            aqtion-${{github.ref_name}}-linux-x86_64.deb 

      - name: Generate Linux ARM64 deb archive
        uses: actions/upload-artifact@v3
        with:
          name: linux-${{github.ref_name}}-arm64-deb
          path: |
            aqtion-${{github.ref_name}}-linux-arm64.deb

      - name: Upload dist tarball to release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          body_path: 
          tag_name: ${{github.ref_name}}
          files: |
            aqtion-${{github.ref_name}}-linux-arm64.deb
            aqtion-${{github.ref_name}}-linux-x86_64.deb

  win_x86_64_dist:
    needs: content_only
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          repository: actionquake/distrib
          path: ${{ env.DIST_DIR }}

      - name: Get aqtion-content
        uses: actions/download-artifact@v3
        with:
          name: aqtion-${{github.ref_name}}-content-only
          path: ${{ env.AQTION_DIR }}

      - name: Download and extract latest Windows Q2Pro Release
        run: |
          wget -qnv https://github.com/actionquake/q2pro/releases/latest/download/q2pro-msvc-x64.zip
          unzip q2pro-msvc-x64.zip -d ${{ env.AQTION_DIR }}

      - name: Copy external libraries for Q2Pro
        run: |
          cp ${{ env.DIST_DIR }}/build/windows/integrations/* ${{ env.AQTION_DIR }}

      - name: Upload aqtion-windows-x86_64 archive
        uses: actions/upload-artifact@v3
        with:
          name: aqtion-${{github.ref_name}}-windows-x86_64
          path: |
            ${{ env.AQTION_DIR }}/*

      - name: Generate release artifact
        run: |
          zip -r aqtion-${{github.ref_name}}-windows-x86_64.zip ${{ env.AQTION_DIR }}

      - name: Upload dist tarball to release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          body_path: 
          tag_name: ${{github.ref_name}}
          files: |
            aqtion-${{github.ref_name}}-windows-x86_64.zip

  lin_x86_64_dist:
    needs: content_only
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          repository: actionquake/distrib
          path: ${{ env.DIST_DIR }}

      - name: Get aqtion-content
        uses: actions/download-artifact@v3
        with:
          name: aqtion-${{github.ref_name}}-content-only
          path: ${{ env.AQTION_DIR }}

      - name: Download and extract latest Linux x64 Q2Pro Release
        run: |
          wget -qnv https://github.com/actionquake/q2pro/releases/latest/download/q2pro-lin-gcc.zip
          unzip q2pro-lin-gcc.zip -d ${{ env.AQTION_DIR }}
          chmod +x ${{ env.AQTION_DIR }}/q2pro*

      - name: Copy external libraries for Q2Pro
        run: |
          cp ${{ env.DIST_DIR }}/build/linux/integrations/* ${{ env.AQTION_DIR }}

      - name: Upload aqtion-linux-x86_64 archive
        uses: actions/upload-artifact@v3
        with:
          name: aqtion-${{github.ref_name}}-linux-x86_64
          path: |
            ${{ env.AQTION_DIR }}/*

      - name: Generate release artifact
        run: |
          zip -r aqtion-${{github.ref_name}}-linux-x86_64.zip ${{ env.AQTION_DIR }}

      - name: Upload dist tarball to release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          body_path: 
          tag_name: ${{github.ref_name}}
          files: |
            aqtion-${{github.ref_name}}-linux-x86_64.zip

  lin_arm64_dist:
    needs: content_only
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          repository: actionquake/distrib
          path: ${{ env.DIST_DIR }}

      - name: Get aqtion-content
        uses: actions/download-artifact@v3
        with:
          name: aqtion-${{github.ref_name}}-content-only
          path: ${{ env.AQTION_DIR }}

      - name: Copy external libraries for Q2Pro
        run: |
          cp ${{ env.DIST_DIR }}/build/linux/integrations/* ${{ env.AQTION_DIR }}

      - name: Upload aqtion-linux-arm64 archive
        uses: actions/upload-artifact@v3
        with:
          name: aqtion-${{github.ref_name}}-linux-arm64
          path: |
            ${{ env.AQTION_DIR }}/*

      - name: Generate release artifact
        run: |
          zip -r aqtion-${{github.ref_name}}-linux-arm64.zip ${{ env.AQTION_DIR }}

      - name: Upload dist tarball to release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          body_path: 
          tag_name: ${{github.ref_name}}
          files: |
            aqtion-${{github.ref_name}}-linux-arm64.zip

  mac_dist:
    needs: content_only
    runs-on: macos-latest
    steps:
      - name: Checkout distrib
        uses: actions/checkout@v3
        with:
          repository: actionquake/distrib
          path: ${{ env.DIST_DIR }}

      - name: Get aqtion-content
        uses: actions/download-artifact@v3
        with:
          name: aqtion-${{github.ref_name}}-content-only
          path: ${{ env.AQTION_DIR }}

      # Standalone
      - name: Generate Mac Standalone artifacts
        working-directory: ${{ env.DIST_DIR }}/build/mac
        run: |
          bash -x package_mac.sh standalone

      - name: Generate Universal Standalone DMG artifact
        uses: actions/upload-artifact@v3
        with:
          name: aqtion-${{github.ref_name}}-mac-universal
          path: |
            ${{ env.DIST_DIR }}/build/mac/aqtion-mac-universal-standalone.dmg

      # Steam
      - name: Generate Mac Steam artifacts
        working-directory: ${{ env.DIST_DIR }}/build/mac
        run: bash -x package_mac.sh steam

      - name: Generate Universal Steam zip artifact
        uses: actions/upload-artifact@v3
        with:
          name: aqtion-${{github.ref_name}}-mac-universal-steam
          path: |
            ${{ env.DIST_DIR }}/build/mac/Steam_Install

      - name: Generate release artifact
        run: |
          mv ${{ env.DIST_DIR }}/build/mac/aqtion-mac-universal-standalone.dmg aqtion-${{github.ref_name}}-mac-universal.dmg

      - name: Upload dist tarball to release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          body_path: 
          tag_name: ${{github.ref_name}}
          files: |
            aqtion-${{github.ref_name}}-mac-universal.dmg


  push_to_release:
    needs: ["mac_dist", "lin_x86_64_dist", "win_x86_64_dist", "lin_arm64_dist", "linux_deb", "content_only"]
    runs-on: ubuntu-22.04
    steps:
      - name: Update Vercel download links
        run: curl -X POST ${{ secrets.DEPLOY_API_URL }}
  #     - name: Get Mac Universal DMG artifact
  #       uses: dawidd6/action-download-artifact@v2
  #       with:
  #         name: aqtion-${{github.ref_name}}-mac-universal
  #         skip_unpack: false

  #     - name: Get Linux ARM64 artifact
  #       uses: dawidd6/action-download-artifact@v2
  #       with:
  #         name: aqtion-${{github.ref_name}}-linux-arm64
  #         skip_unpack: true

  #     - name: Get Linux x86_64 artifact
  #       uses: dawidd6/action-download-artifact@v2
  #       with:
  #         name: aqtion-${{github.ref_name}}-linux-x86_64
  #         skip_unpack: true

  #     - name: Get Windows x86_64 artifact
  #       uses: dawidd6/action-download-artifact@v2
  #       with:
  #         name: aqtion-${{github.ref_name}}-windows-x86_64
  #         skip_unpack: true

  #     - name: Get Linux x86_64 DEB artifact
  #       uses: dawidd6/action-download-artifact@v2
  #       with:
  #         name: linux-${{github.ref_name}}-x86_64-deb
  #         skip_unpack: false

  #     - name: Get Linux arm64 DEB artifact
  #       uses: dawidd6/action-download-artifact@v2
  #       with:
  #         name: linux-${{github.ref_name}}-arm64-deb
  #         skip_unpack: false

  #     - name: Get content-only artifact
  #       uses: dawidd6/action-download-artifact@v2
  #       with:
  #         name: aqtion-${{github.ref_name}}-content-only
  #         skip_unpack: true

  #     - name: Unzip Mac and Deb archives, rename
  #       run: |
  #         unzip aqtion-${{github.ref_name}}-mac-universal
  #         unzip linux-${{github.ref_name}}-x86_64-deb
  #         unzip linux-${{github.ref_name}}-arm64-deb
  #         mv aqtion-mac-universal-standalone.dmg aqtion-${{github.ref_name}}-mac-universal.dmg
   
  #     - name: Look around
  #       run: |
  #         ls -l

  #     - name: Upload dist tarball to release
  #       uses: softprops/action-gh-release@v1
  #       env:
  #         GITHUB_TOKEN: ${{ github.token }}
  #       with:
  #         body_path: 
  #         tag_name: ${{github.ref_name}}
  #         files: |
  #           aqtion-${{github.ref_name}}-content-only.zip
  #           aqtion-${{github.ref_name}}-mac-universal.dmg
  #           aqtion-${{github.ref_name}}-linux-arm64.zip
  #           aqtion-${{github.ref_name}}-linux-x86_64.zip
  #           aqtion-${{github.ref_name}}-windows-x86_64.zip
  #           aqtion-${{github.ref_name}}-linux-x86_64.deb
  #           aqtion-${{github.ref_name}}-linux-arm64.deb


