name: New Steam Release

on: 
  workflow_dispatch:
    inputs:
      steam_branch:
        description: 'Branch to deploy in Steam'     
        required: true
        default: 'playtest' 
        type: choice
        options:
        - playtest
        - stattest
      release_tag:
        description: "Release version tag (ex: v1.2.3)"
        required: true

env:
  CFG_WORKING_DIR: "config"
  LIN64_DIST_DIR: "linux-x64-dist"
  WIN64_DIST_DIR: "windows-x64-dist"
  MAC_DIST_DIR: "mac-universal-dist"

jobs:      
  steam_release:
    runs-on: [self-hosted, x86] ##  Must run on self-hosted due to Steam login credential weirdness
    steps:
      - name: 'Cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./

      - name: Download Linux release package
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow_conclusion: success
          workflow: New-Dist-Release.yaml
          name: aqtion-${{ inputs.release_tag }}-linux-x86_64
          skip_unpack: true
          path: ${{ env.LIN64_DIST_DIR }}/

      - name: Download Windows release package
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow_conclusion: success
          workflow: New-Dist-Release.yaml
          name: aqtion-${{ inputs.release_tag }}-windows-x86_64
          skip_unpack: true
          path: ${{ env.WIN64_DIST_DIR }}/

      - name: Download Mac release package
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow_conclusion: success
          workflow: New-Dist-Release.yaml
          name: aqtion-${{ inputs.release_tag }}-mac-universal-steam
          skip_unpack: true
          path: ${{ env.MAC_DIST_DIR }}/

      - name: Look around
        run: |
          ls -l
          ls -l ${{ env.LIN64_DIST_DIR }}/
          ls -l ${{ env.WIN64_DIST_DIR }}/
          ls -l ${{ env.MAC_DIST_DIR }}/

      # ## Upload to Steam
      # - name: Copy VDF scripts
      #   run: |
      #     cp ${{ env.CFG_WORKING_DIR }}/scripts/steam/*.vdf .

      # - name: Upload All Builds
      #   run: steamcmd +login ${STEAM_LOGIN_NAME} ${STEAM_LOGIN_PASSWORD} +run_app_build /home/github/actions-runner/_work/distrib/distrib/${{ inputs.steam_branch }}.vdf +quit
      #   env:
      #     STEAM_LOGIN_NAME: ${{ secrets.STEAM_LOGIN_NAME }}
      #     STEAM_LOGIN_PASSWORD: ${{ secrets.STEAM_LOGIN_PASSWORD }}

      # - name: 'Post-build cleanup build folder'
      #   run: |
      #     ls -la ./
      #     rm -rf ./* || true
      #     rm -rf ./.??* || true
      #     ls -la ./