name: Linux Q2Pro (64-bit)

# on:
#   push:
#     branches: [main, ci]
#   pull_request:
#     branches: [main]

on:
  workflow_dispatch:

jobs:
  linux_build_q2pro:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    strategy:
      matrix:
        cc: [gcc]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: skullernet/q2pro
          path: build

      # Self-hosted runner has these
      # - name: Install dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt install -y libsdl2-dev libopenal-dev \
      #     libpng-dev libjpeg-dev zlib1g-dev mesa-common-dev \
      #     libcurl4-gnutls-dev

      - uses: actions/checkout@v3
        with:
          repository: actionquake/distrib
          path: config

      - name: Copy config build files
        run: |
          cp -r config/build/ci/config_linux64 build/.config

      - name: Build Q2Pro
        working-directory: build
        run: make V=1
        env:
          CC: "${{ matrix.cc }}"
          CONFIG_FILE: ".config"
      
      - name: Generate archive
        uses: actions/upload-artifact@v3
        with:
          name: q2pro-lin-executables
          path: |
            build/q2pro
            build/q2proded
