name: Quick Release

# on:
#   push:
#     branches: [main, ci]
#   pull_request:
#     branches: [main]

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release version tag"
        required: true

env:
  CFG_WORKING_DIR: "config"
  LIN64_DIST_DIR: "linux-x64-dist"
  LINARM64_DIST_DIR: "linux-arm64-dist"
  WIN64_DIST_DIR: "windows-x64-dist"
  WIN32_DIST_DIR: "windows-i386-dist"
  GIT_TAG: ${{ github.event.inputs.release_tag }}

jobs:      
  quick_release:
    runs-on: ubuntu-latest
    #runs-on: self-hosted
    steps:
      - name: Checkout distrib
        uses: actions/checkout@v3
        with:
          repository: actionquake/distrib
          path: ${{ env.CFG_WORKING_DIR }}

      - name: Generate dist directories
        run: |
          mkdir -p ${{ env.LINARM64_DIST_DIR }}/action
          mkdir -p ${{ env.LIN64_DIST_DIR }}/action
          mkdir -p ${{ env.WIN64_DIST_DIR }}/action
          mkdir -p ${{ env.WIN32_DIST_DIR }}/action

      ## Linux x86_64
      - name: Download latest Linux x86_64 Q2Pro artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: Q2Pro-Linux.yaml
          name: q2pro-linux-x86_64
          path: ${{ env.LIN64_DIST_DIR }}/

      - name: Set Linux binaries to executable
        run: |
          chmod +x ${{ env.LIN64_DIST_DIR }}/*

      - name: Download latest Linux x86_64 TNG artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: TNG-Linux.yaml
          name: tng-lin-x86_64-library
          path: ${{ env.LIN64_DIST_DIR }}/action/

      - name: Copy action content
        run: |
          cp -r ${{ env.CFG_WORKING_DIR }}/action/* ${{ env.LIN64_DIST_DIR }}/action/

      ## Linux ARM64
      - name: Download latest Linux arm64 Q2Pro artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: Q2Pro-Linux.yaml
          name: q2pro-linux-arm64
          path: ${{ env.LINARM64_DIST_DIR }}/

      - name: Set Linux binaries to executable
        run: |
          chmod +x ${{ env.LINARM64_DIST_DIR }}/*

      - name: Download latest Linux arm64 TNG artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: TNG-Linux.yaml
          name: tng-lin-arm64-library
          path: ${{ env.LINARM64_DIST_DIR }}/action/

      - name: Copy action content
        run: |
          cp -r ${{ env.CFG_WORKING_DIR }}/action/* ${{ env.LINARM64_DIST_DIR }}/action/

      ## Win32
      - name: Download latest Win32 Q2Pro artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: Q2Pro-Windows.yaml
          name: q2pro-win-32
          path: ${{ env.WIN32_DIST_DIR }}/

      - name: Download latest Win32 TNG artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: TNG-Windows.yaml
          name: tng-win-32
          path: ${{ env.WIN32_DIST_DIR }}/action/

      - name: Copy action content
        run: |
          cp -r ${{ env.CFG_WORKING_DIR }}/action/* ${{ env.WIN32_DIST_DIR }}/action/

      ## Win64
      - name: Download latest Win64 Q2Pro artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: Q2Pro-Windows.yaml
          name: q2pro-win-64
          path: ${{ env.WIN64_DIST_DIR }}/

      - name: Download latest Win64 TNG artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: TNG-Windows.yaml
          name: tng-win-64
          path: ${{ env.WIN64_DIST_DIR }}/action/

      - name: Copy action content
        run: |
          cp -r ${{ env.CFG_WORKING_DIR }}/action/* ${{ env.WIN64_DIST_DIR }}/action/
      
      - name: Download latest Content-only archive
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: Content-Only.yaml
          name: aq-content-only

      - name: Generate content-only zip file
        run: |
          mv aqtion-content.zip aqtion-content-${{ env.GIT_TAG }}.zip

      ## Can't install .deb to normal user dirs, wtf Linux?
      # - name: Generate Linux deb files
      #   run: |
      #     mkdir -p aqtion-${{ env.GIT_TAG }}/usr/local/games
      #     mkdir -p aqtion-${{ env.GIT_TAG }}/DEBIAN
      #     cp ${{ env.CFG_WORKING_DIR }}/build/linux/DEBIAN/* aqtion-${{ env.GIT_TAG }}/DEBIAN
      #     cp -r ${{ env.LIN64_DIST_DIR }}/* aqtion-${{ env.GIT_TAG }}/usr/local/games/
      #     sed -i "s/version_value_here/${GIT_TAG:1}/g" aqtion-${{ env.GIT_TAG }}/DEBIAN/control
      #     dpkg-deb --build --root-owner-group aqtion-${{ env.GIT_TAG }}
      #     mv aqtion-${{ env.GIT_TAG }}.deb aqtion-${{ env.GIT_TAG }}-linux-amd64.deb

      - name: Get version info for distrib
        id: version
        run: |
          cd config/build
          bash -x getversion.sh distrib >> ../../${{ env.LIN64_DIST_DIR }}/versions
          bash -x getversion.sh distrib >> ../../${{ env.LINARM64_DIST_DIR }}/versions
          bash -x getversion.sh distrib >> ../../${{ env.WIN64_DIST_DIR }}/versions
          bash -x getversion.sh distrib >> ../../${{ env.WIN32_DIST_DIR }}/versions

      - name: Combine version info into single files
        run: |
          cat ${{ env.LIN64_DIST_DIR }}/q2admin/versions >> ${{ env.LIN64_DIST_DIR }}/versions
          cat ${{ env.LIN64_DIST_DIR }}/tng/versions >> ${{ env.LIN64_DIST_DIR }}/versions
          echo "aqtion_distrib-version=${{ env.GIT_TAG }}" >> ${{ env.LIN64_DIST_DIR }}/versions

          cat ${{ env.LINARM64_DIST_DIR }}/q2admin/versions >> ${{ env.LINARM64_DIST_DIR }}/versions
          cat ${{ env.LINARM64_DIST_DIR }}/tng/versions >> ${{ env.LINARM64_DIST_DIR }}/versions
          echo "aqtion_distrib-version=${{ env.GIT_TAG }}" >> ${{ env.LINARM64_DIST_DIR }}/versions

          cat ${{ env.WIN64_DIST_DIR }}/q2admin/versions >> ${{ env.WIN64_DIST_DIR }}/versions
          cat ${{ env.WIN64_DIST_DIR }}/tng/versions >> ${{ env.WIN64_DIST_DIR }}/versions
          echo "aqtion_distrib-version=${{ env.GIT_TAG }}" >> ${{ env.WIN64_DIST_DIR }}/versions

          cat ${{ env.WIN32_DIST_DIR }}/q2admin/versions >> ${{ env.WIN32_DIST_DIR }}/versions
          cat ${{ env.WIN32_DIST_DIR }}/tng/versions >> ${{ env.WIN32_DIST_DIR }}/versions
          echo "aqtion_distrib-version=${{ env.GIT_TAG }}" >> ${{ env.WIN32_DIST_DIR }}/versions

      - name: Generate Linux tar files
        run: |
          tar czpf aqtion-${{ env.GIT_TAG }}-linux-amd64.tar.gz ${{ env.LIN64_DIST_DIR }}
          tar czpf aqtion-${{ env.GIT_TAG }}-linux-arm64.tar.gz ${{ env.LINARM64_DIST_DIR }}

      - name: Generate Windows zip files
        run: |
          zip -r aqtion-${{ env.GIT_TAG }}-windows-x64.zip ${{ env.WIN64_DIST_DIR }}
          zip -r aqtion-${{ env.GIT_TAG }}-windows-i386.zip ${{ env.WIN32_DIST_DIR }}
    
      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: aqtion-${{ github.event.inputs.release_tag }}
          tag_name: ${{ github.event.inputs.release_tag }}
          #body_path: CHANGELOG.md
          body: ${{steps.github_release.outputs.changelog}}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload dist tarball to release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          body_path: 
          tag_name: ${{ github.event.inputs.release_tag }}
          files: |
            aqtion-${{ env.GIT_TAG }}-linux-arm64.tar.gz
            aqtion-${{ env.GIT_TAG }}-linux-amd64.tar.gz
            aqtion-${{ env.GIT_TAG }}-windows-x64.zip
            aqtion-${{ env.GIT_TAG }}-windows-i386.zip
            aqtion-content-${{ env.GIT_TAG }}.zip

