name: Release

# on:
#   push:
#     branches: [main, ci]
#   pull_request:
#     branches: [main]

on:
  workflow_dispatch:

jobs:
  generate_release:
    runs-on: self-hosted
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3

      - name: Look around
        run: ls -l build
