name: Windows TNG (32/64-bit)

on:
  push:
    branches: ci
  workflow_dispatch:

# on:
#   workflow_dispatch:

jobs:
  windows_build_tng:
    runs-on: [self-hosted, x86]
    steps:
      - uses: actions/checkout@v3
        with:
          # repository: aq2-tng/aq2-tng  ## Official repository
          repository: actionquake/aq2-tng
          ref: 'aqtion'
          path: build

      - uses: actions/checkout@v3
        with:
          repository: actionquake/distrib
          path: config

      # This is because the Makefile doesn't recognize mingw on Linux, and we have to append a special flag at the linking step for Windows
      # - name: Rough hack to fix Makefile
      #   run: |
      #     mv build/source/Makefile build/source/Makefile-original
      #     cat config/build/windows/tng-windows-append build/source/Makefile-original > build/source/Makefile

      - name: Get version info for tng
        id: version
        run: |
          cp config/build/getversion.sh build/
          cd build && bash -x getversion.sh tng >> versions

      - name: Build TNG (64-bit)
        working-directory: build/source
        run: make -j4 V=1 && mv gamex86_64.dll ../gamex86_64.dll
        env:
          TNG_BUILD_FOR: "WIN64"
          AQTION: "TRUE"

      - name: Generate Win64 archive
        uses: actions/upload-artifact@v3
        with:
          name: tng-win-64
          path: |
            build/gamex86_64.dll
            build/versions

      - name: Build TNG (32-bit)
        working-directory: build/source
        run: make clean && make -j4 V=1 && mv gamex86.dll ../gamex86.dll
        env:
          TNG_BUILD_FOR: "WIN32"
          AQTION: "TRUE"

      - name: Generate Win32 archive
        uses: actions/upload-artifact@v3
        with:
          name: tng-win-32
          path: |
            build/gamex86.dll
            build/versions

      - name: 'Post-build cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./