name: Linux TNG (64-bit)

# on:
#   push:
#     branches: [main, ci]
#   pull_request:
#     branches: [main]

on:
  workflow_dispatch:

jobs:
  linux_build_tng:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          repository: aq2-tng/aq2-tng
          ref: 'bots'
          path: build

      - name: Build TNG
        working-directory: build/source
        run: make V=1
        env:
          CC: "gcc"

      - name: Generate archive
        uses: actions/upload-artifact@v3
        with:
          name: tng-lin-library
          path: |
            build/source/gamex86_64.so